#ifndef HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED
#define HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED

#ifndef _Static_assert
#ifdef _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0
#error "`_HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0` mustn't be pre-defined"
#endif // _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0
#ifdef _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1
#error "`_HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1` mustn't be pre-defined"
#endif // _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1

#ifdef __STDC_VERSION__
#if __STDC_VERSION__ >= 201112L
#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0(condition) \
    _Static_assert(condition, "")

#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1(condition, message) \
    _Static_assert(condition, message)
#elif __STDC_VERSION__ >= 202311L
#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0(condition) \
    static_assert(condition)

#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1(condition, message) \
    static_assert(condition, message)
#endif // __STDC_VERSION__ < 201112L
#endif // __STDC_VERSION__

#ifndef _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0
#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0(_1)
#endif // _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0
#ifndef _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1
#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1(_1, _2)
#endif // _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1

#define _HERBARY_STD_DEFINE__STATIC_ASSERT_H_GET_STATIC_ASSERT_IMPL(_1, _2, macro, ...) \
    macro

#define _Static_assert(...) \
    _HERBARY_STD_DEFINE__STATIC_ASSERT_H_GET_STATIC_ASSERT_IMPL(__VA_ARGS__, \
        _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_1, \
        _HERBARY_STD_DEFINE__STATIC_ASSERT_H_STATIC_ASSERT_IMPL_0, \
        0 /* Dummy value to suppress the `-Wgnu-zero-variadic-macro-arguments` */ \
    )(__VA_ARGS__)
#endif // _Static_assert

#endif // HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED
